//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clientSide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScrapeTable
    {
        public int Id { get; set; }
        public System.DateTime PullTime { get; set; }
        public string Symbol { get; set; }
        public string LastPrice { get; set; }
        public string Type { get; set; }
        public string ChangePerc { get; set; }
        public string Volume { get; set; }
        public string VolumeAvg { get; set; }
    }
}
